apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: httpd-with-pv
  name: httpd-with-pv
spec:
  replicas: 1
  selector:
    matchLabels:
      run: httpd-with-pv
  template:
    metadata:
      labels:
        run: httpd-with-pv
    spec:
      containers:
        - image: httpd
          name: httpd-with-pv
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: httpd-assets
      volumes:
        - name: httpd-assets
          persistentVolumeClaim:
            claimName: httpd-pvc
