apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jenkins-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-jenkins-slave
  template:
    metadata:
      labels:
        run: my-jenkins-slave
    spec:
      containers:
        - image: jenkins/jnlp-slave
          name: my-jenkins-slave
          env:
            - name: JENKINS_URL
              value: http://10.106.10.243:8080
            - name: JENKINS_SECRET
              value: 04c47064a5e0954def8a02cd894a2f8664d6c08a0d57940afec804d3c7d9211e
            - name: JENKINS_AGENT_NAME
              value: slave1