apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      release: "stable"