apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: my-jenkins-slave
  name: my-jenkins-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-jenkins-slave
  template:
    metadata:
      labels:
        run: my-jenkins-slave
    spec:
      containers:
        - image: jenkins/jnlp-slave
          name: my-jenkins-slave
          resources: {}
          env:
            - name: JENKINS_URL
              value: http://10.108.201.173:8080
            - name: JENKINS_SECRET
              value: fae549698c994966c4ee215a710dfa942d3195b6cc0648c1320a7179b8844986
            - name: JENKINS_AGENT_NAME
              value: agent1