apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: my-jenkins
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jnlp
    port: 50000
    protocol: TCP
    targetPort: 50000	
  selector:
    run: my-jenkins
status:
  loadBalancer: {}